ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "apiKeyHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "apiKeyLast4" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "apiKeyCreatedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "apiKeyRevokedAt" TIMESTAMP(3);
CREATE UNIQUE INDEX IF NOT EXISTS "User_apiKeyHash_key" ON "User"("apiKeyHash");
